### PR TITLE
Update URLUtils.ts

### PR DESCRIPTION
**Pull request by themsquared**
Change `service` to `entity` as this is the new correct link.

## Change description

> Description here

## Type of change

- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)
- [ ] Improvement (improves codebase without changing functionality)

## Related issues

> Fix [#1]()

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

### CODE REVIEW

**Review by nikhilunni — APPROVED** [review]
hell yeah! could you also bump the version in `package.json`? it'll auto publish a new version of the plugin

**Review by cristinabuenahora — APPROVED** [review]

**Review by cristinabuenahora — CHANGES_REQUESTED** [review]
Need to update the package.json file

**Comment by themsquared** [comment]
> Need to update the package.json file

Should I bump the version? Sorry just don't do this often lol

**Comment by imundra** [comment]
> > Need to update the package.json file
> 
> Should I bump the version? Sorry just don't do this often lol

yup just bump the version

**Comment by FoodProduct** [comment]
Yup just update this line to 1.7.3 https://github.com/cortexapps/backstage-plugin/blob/04716eb37e30dc798ce6a6cdf84107c1ab459c77/package.json#L3

**Pull request closed without merging**
