### PR TITLE
Remove Ladders:  PR 2/3 Part1

### PR DESCRIPTION
**Pull request by maddymanu**
## Change description

> Description here

## Type of change

- [ ] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)
- [ ] Improvement (improves codebase without changing functionality)

## Related issues

> Fix [#1]()

### Development

- [ ] Lint rules pass locally
- [ ] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [ ] Security impact of change has been considered
- [ ] Code follows company security practices and guidelines

### Code review

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

### CODE REVIEW

**Review by cristinabuenahora — APPROVED** [review]

**Comment by cristinabuenahora** [comment]
You'll need to update the package.json file

**Review by FoodProduct — CHANGES_REQUESTED** [review]
Please bump the version in package.json (as Cristina mentioned)

**Comment by maddymanu** [comment]
> Please bump the version in package.json (as Cristina mentioned)

I bumped the minor version. These keys weren't used anywhere, so Im guessing the auto-upgrade should be fine!

**Review by FoodProduct — APPROVED** [review]
That's the patch version, not the minor version 🙂

**Comment by maddymanu** [comment]
> That's the patch version, not the minor version 🙂

ahhh yes. I'm always getting confused 😅

**Pull request merged**
